### ISSUE TITLE
Does not work for elements without an ID attribute

### ISSUE THREAD

**Issue by rajeshgsoni** [Med072356/savy#5]
Hello @medabida, Savy does not work for elements without an ID attribute. 
I've patched the code locally and this is what I have come up with a workaround for elements that do NOT have an "id" specified.

savy.js line # 6
add this 
`		  if(!this.id) this.id = $(this).attr("name");  `
after
`    if (order == "load") {
      $(this).each(function() {
`

so final code is
`
    if (order == "load") {
      $(this).each(function() {
		  if(!this.id) this.id = $(this).attr("name");
        if ($(this).is(":radio")) {
`
![Screenshot 2022-09-27 192853](https://user-images.githubusercontent.com/348228/192547116-c7a66412-e4a3-44ff-8281-1edfa56fadc5.jpg)

Hope this helps
~Rajesh

**Comment by medabida** [comment]
Hi Rajesh, the latest version of Savy should handle this correctly.
